backend:
  name: git-gateway
  branch: cimusa # Branch to update (optional; defaults to master)
logo_url: "/images/Flag_of_Côte_d'Ivoire.svg"
# This line should *not* be indented
publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - label: "FAQ"
    name: "faq"
    files:
      - label: "FAQ (en)"
        name: "faq (en)"
        file: "data/en/faq.yml"
        fields:
          - label: FAQ (en)
            name: faqItem
            widget: list
            fields:
              - {label: ID, name: ID, widget: select, options: ["collapseOne", "collapseTwo", "collapseThree", "collapseFour", "collapseFive", "collapseSix", "collapseSeven", "collapseHeight"]}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
      - label: "FAQ (fr)"
        name: "faq (fr)"
        file: "data/fr/faq.yml"
        fields:
          - label: FAQ (fr)
            name: faqItem
            widget: list
            fields:
              - {label: ID, name: ID, widget: select, options: ["collapseOne", "collapseTwo", "collapseThree", "collapseFour", "collapseFive", "collapseSix", "collapseSeven", "collapseHeight"]}
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: string}
  # Blog Collections
  - label: "Blog in English"
    name: "english_posts"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Blog en Francais"
    name: "posts_francais"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Langue", name: "language", widget: "hidden", default: "fr"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  # Events
  - label: "Events"
    name: "english_events"
    folder: "content/events"
    create: true
    fields:
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Evènements"
    name: "events_francais"
    folder: "content/events"
    create: true
    fields:
      - {label: "Langue", name: "language", widget: "hidden", default: "fr"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
  # Membership Contributions
  - label: "Membership and Contributions"
    name: "english_membershipcontribs"
    folder: "content/membership-contributions"
    create: true
    fields:
      - {label: "Language", name: "language", widget: "hidden", default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Adhésion et Contributions"
    name: "membershipcontribs_francais"
    folder: "content/membership-contributions"
    create: true
    fields:
      - {label: "Langue", name: "language", widget: "hidden", default: "fr"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Type", name: "type", widget: "hidden", default: "post"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}

